### ISSUE TITLE
专业号的查看方式

### ISSUE THREAD

**Issue by Orderheart** [LittFlower/SCU-URP-Helper#3]
亲爱的作者大大你好，请问专业号可以从jwc的哪个地方查找哩？

**Comment by Orderheart** [comment]
经过测试，只需要填写账号和密码即可完成程序的正常运行，无需填写专业号

**Comment by LittFlower** [comment]
确实，@Y0oMu 和你抱同样的观点，只是我还不太确认。

专业号是用 post 方式上传的，可以参考这篇文章使用浏览器获取专业号。

https://www.cnblogs.com/yancongyang/p/8142669.html

**Comment by LittFlower** [comment]
well，如果专业号填错的话，选课时可能会出现脚本抢到课但是教务系统查看不到课的情况。
