### ISSUE TITLE
安装了相关的包但是提示没有找到

### ISSUE THREAD

**Issue by scu-winner** [LittFlower/SCU-URP-Helper#4]
已经下载了，但是无法运行

**Comment by LittFlower** [comment]
“安装了相关的包”，具体是哪个包呢？“提示没有找到”，哪个包没有找到？“无法运行”，你没有提供报错和日志。

你是什么操作系统，python版本多少，用没用虚拟环境，请提供必要的信息。

**Comment by LittFlower** [comment]
“安装了相关的包”，具体是哪个包呢？“提示没有找到”，哪个包没有找到？“无法运行”，你没有提供报错和日志。

你是什么操作系统，python版本多少，用没用虚拟环境，请提供必要的信息。

**Comment by LittFlower** [comment]
![Screenshot_20240617_193142.jpg](https://github.com/LittFlower/SCU-URP-Helper/assets/75172736/295f5884-c85b-4d06-bf69-76c0d4fb7228)

json 包不需要安装，是 python 自带的，和小版本无关。

另外，提问之前请阅读提问的智慧。

**Comment by Orderheart** [comment]
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by Orderheart** [comment]
请参考《提问的智慧》：https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
