### ISSUE TITLE
专业号在哪里查找呢

### ISSUE THREAD

**Issue by d2andna** [LittFlower/SCU-URP-Helper#5]
![1718801564466](https://github.com/LittFlower/SCU-URP-Helper/assets/171028536/326dddde-6bdf-439f-aa47-95c88d719368)

**Comment by LittFlower** [comment]
专业号是用 post 方式上传的，可以参考这篇文章使用浏览器获取专业号。

https://www.cnblogs.com/yancongyang/p/8142669.html

**Comment by d2andna** [comment]
感谢！！
